//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace napravo_schedule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("napravo_schedule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;idClass&quot;: 4,
        ///    &quot;subjectTitle&quot;: &quot;Математика&quot;,
        ///    &quot;teacherName&quot;: &quot;Василий Василиевич Васильков&quot;,
        ///    &quot;groupTitle&quot;: &quot;Вп-31&quot;,
        ///    &quot;time&quot;: 540,
        ///    &quot;dayOfWeek&quot;: 1
        ///  },
        ///  {
        ///    &quot;idClass&quot;: 5,
        ///    &quot;subjectTitle&quot;: &quot;Физика&quot;,
        ///    &quot;teacherName&quot;: &quot;Василий Василиевич Васильков&quot;,
        ///    &quot;groupTitle&quot;: &quot;Вп-31&quot;,
        ///    &quot;time&quot;: 640,
        ///    &quot;dayOfWeek&quot;: 1
        ///  },
        ///  {
        ///    &quot;idClass&quot;: 6,
        ///    &quot;subjectTitle&quot;: &quot;Unity&quot;,
        ///    &quot;teacherName&quot;: &quot;Василий Василиевич Васильков&quot;,
        ///    &quot;groupTitle&quot;: &quot;Вп-31&quot;,
        ///    &quot;time&quot;: 7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string crap {
            get {
                return ResourceManager.GetString("crap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;idNotification&quot;: 2,
        ///    &quot;idStudent&quot;: 1,
        ///    &quot;header&quot;: &quot;Результаты экзамена&quot;,
        ///    &quot;message&quot;: &quot;У вас 2&quot;,
        ///    &quot;moment&quot;: &quot;2023-06-15T00:00:00&quot;,
        ///    &quot;isChecked&quot;: true
        ///  },
        ///  {
        ///    &quot;idNotification&quot;: 4,
        ///    &quot;idStudent&quot;: 1,
        ///    &quot;header&quot;: &quot;Средний балл по вашей группе ниже 2.78&quot;,
        ///    &quot;message&quot;: &quot;Вы близки к своему отчислению&quot;,
        ///    &quot;moment&quot;: &quot;2023-06-16T00:00:00&quot;,
        ///    &quot;isChecked&quot;: false
        ///  }
        ///].
        /// </summary>
        public static string notif {
            get {
                return ResourceManager.GetString("notif", resourceCulture);
            }
        }
    }
}
